CREATE DATABASE passman;

USE passman; 

CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    username VARCHAR(50) NOT NULL,
    creationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT password_id FOREIGN KEY (id) REFERENCES passwords(id)
);

CREATE TABLE passwords (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    creationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modiifedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT domain_id FOREIGN KEY (id) REFERENCES domains(id),
    CONSTRAINT tag_id FOREIGN KEY (id) REFERENCES tags(id)
);

CREATE TABLE domains (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    domain VARCHAR(255) NOT NULL
);

CREATE TABLE tags (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(50) NOT NULL,
    creationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modiifedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);