CREATE DATABASE passman;

USE passman;

CREATE TABLE users (
    id PRIMARY KEY AUTO_INCREMENT NOT NULL,
    username VARCHAR(50) NOT NULL,
    creationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (password_id) REFERENCES passwords(id)
);

CREATE TABLE passwords (
    id PRIMARY KEY AUTO_INCREMENT NOT NULL,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    creationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modiifedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (domain_id) REFERENCES domains(id),
    FOREIGN KEY (tag_id) REFERENCES tags(id)
);

CREATE TABLE domains (
    id PRIMARY KEY AUTO_INCREMENT NOT NULL,
    domain VARCHAR(255) NOT NULL
);

CREATE TABLE tags (
    id PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(50) NOT NULL,
    creationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modiifedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

